# Dockerfile for React client

# Build react client
FROM node as build

# Working directory be app
WORKDIR /app

COPY package.json .

###  Installing dependencies

RUN npm install 

# copy local files to app folder
COPY . .

RUN npm run build

FROM nginx
COPY --from=build /app/build /usr/share/nginx/html